name: "Run MEND scan"
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WS_APIKEY: ${{ secrets.WS_APIKEY }}
  WS_USERKEY: ${{ secrets.WS_USERKEY }}
  WS_PRODUCTNAME: ${{ secrets.WS_PRODUCTNAME }}
  WS_PROJECTNAME: ${{ secrets.WS_PROJECTNAME }}
  WS_WSS_URL: ${{ secrets.WS_WSS_URL }}
  

jobs:
  mend-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'microsoft'
          
      - name: Download the mend scan jar
        run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      
      - name: Run the mend scan jar
        run: |
          java -jar wss-unified-agent.jar -d ${{ github.workspace }}